apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    name: app
    app: nginxjs
    color: green
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: green
      name: app
  template:
    metadata:
      name: green
      labels:
        name: app
        app: nginxjs
        color: green
    spec:
      containers:
      - image: docker.io/takuyak/nginx-sample-gr:v1
        name: green
        ports:
          - containerPort: 80
